### ISSUE TITLE
Browsing users through Admin raises "KeyError: username"

### ISSUE THREAD

**Issue by andreyshipilov** [celiao/django-rest-authemail#10]
Browsing urls like /appname/customusermodel/1/

...venv/lib/python2.7/site-packages/authemail/forms.py in **init**
Line 55 — del self.fields['username'] 

Commenting this line out temporarily fixes it.

Should the "username" be in the fields at all? If the custom user model is inherited from EmailAbstractUser and before that from AbstractBaseUser — both of them don't have the "username" field.

**Comment by celiao** [comment]
This is a continuation of Issue #9.  Please see Issue #9.
