### ISSUE TITLE
how to store username too during signup

### ISSUE THREAD

**Issue by sabarirangan** [celiao/django-rest-authemail#15]
i have the following model
class MyUser(EmailAbstractUser):
    username=models.CharField(max_length=100,unique=True)
    objects = EmailUserManager()

endpoint:-/signup
method:-POST
body:-
{
    "first_name": myfirst",
    "last_name": "mylast",
    "email": "myemail@mail.com",
    "password": "mypassword",
    "username": "myusernaame"
}

but the username doesnot gets stored in MyUser model, how to resolve this.

**Comment by celiao** [comment]
The nice thing about `django-rest-authemail` is that you don't need usernames.  The user logs in with their email address.  If you need to refer to the user, use the instance rather than a string.

If you really want a username, create an endpoint in your custom code for that purpose.
