### ISSUE TITLE
Sign up without email verification.

### ISSUE THREAD

**Issue by tuananhdn** [celiao/django-rest-authemail#16]
I have function login with facebook, it will automatically create user if not exists, but my problem is it will send an email verification to user, can we create a verified user without it?

Thanks.

**Comment by celiao** [comment]
Hey, @tuananhdn.  If you read through [README.rst](https://github.com/celiao/django-rest-authemail/blob/master/README.rst), you will find: `Optionally, you may add a AUTH_EMAIL_VERIFICATION setting to specify whether to enable email verification for new users on account registration/signup. Setting this to False will automatically verify newly created users.`.
