### ISSUE TITLE
Add support for django 3.1

### ISSUE THREAD

**Issue by DeeeeLAN** [celiao/django-rest-authemail#27]
I don't know if anything is required beyond updating the compatible versions. I want to use the new JSONField in my models, but it requires 3.1.

**Comment by celiao** [comment]
@DeeeeLAN 

My plan is to:
1. Update the code to Python 3.7, Django 2.1, and DRF 3.11. - DONE
1. Perform small fixes and clean up the documentation.  - DONE
1. Add GitHub Actions, including unit testing, linting, PyPi uploading, and coverage.  - DONE
1. Address outstanding issues.  - IN PROGRESS -> DONE
1. Address outstanding pull requests.  - DONE
1. Tag the commit at this point, so users of Django 2.1 and below can have the benefit of the above by installing this version. - TO DO -> DONE
    1. Users of Django 2.1 and below should use version `1.10.2`.
1. Update the code for Python 3.8, Django 3.1, and DRF 3.11.  This will make django-rest-authemail compatible with Python 3.6/3.7/3.8, Django 2.2.8+/3.0/3.1, and DRF 3.11 only moving forward. - TO DO -> DONE
1. Try to get package on DRF third-party list.  - WILL DO

I'm getting close!

**Comment by celiao** [comment]
Updated steps 4. and 6. to DONE.  Starting on 7.

**Comment by celiao** [comment]
Version `2.0.4` and above now supports and is  tested with Django 2.2.8, 2.2.13, 3.0, and 3.1.

**Comment by celiao** [comment]
Version `2.0.6` and above now supports and is tested with Python 3.8.

**Comment by celiao** [comment]
Django 3.1 is supported, as requested.  Closing.
