### ISSUE TITLE
setup authenticated user in testing the API

### ISSUE THREAD

**Issue by leunis** [celiao/django-rest-authemail#33]
Hi,

I want to set my tests with using an authenticated user. Normally this works:

```
class PrivateVacanciesApiTests(TestCase):
        """ Test the Private vacancy API"""

        def setUp(self):
            self.client = APIClient()
            self.user = get_user_model().objects.create_user(
                email='test@uxstudio.nl',
                password='testpass123')
            self.client.force_authenticate(self.user)
```

With django-rest-authemail this does not work anymore. Can't find in the documents how this should work. Would be nice if
```
self.client.force_authenticate(self.user) 
```
can work in combination with django-rest-authemail

**Comment by celiao** [comment]
@leunis What error message do you get, i.e., how do you know it doesn't work?

**Comment by celiao** [comment]
Closing this issue due to lack of response.
