### ISSUE TITLE
Pass variable to template via custom context processor

### ISSUE THREAD

**Issue by michaellin986** [celiao/django-rest-authemail#38]
I want to dynamically change the hostname of the link in the email template, so I created a custom template to handle that. I was hoping to pass the hostname to a custom context processor, which would then populate the email template. Unfortunately this doesn't seem to work, and my guess is that `request` is not passed into `render_to_string` [here](https://github.com/celiao/django-rest-authemail/blob/5eb1a2199e6159a9f3c144162e876b1f9a636917/authemail/models.py#L152-L153).

Is there a workaround (aside from creating multiple versions of the templates) or am I missing something?

**Comment by celiao** [comment]
Unfortunately, we don't have `request` defined when `render_to_string()` is called.

You might try modifying your project's `views.py` file to introduce the hostname.
