### ISSUE TITLE
cannot install djangorestframework latest version(3.12.4) along with django-rest-authemail==2.0.6 version

### ISSUE THREAD

**Issue by Avin-Techv** [celiao/django-rest-authemail#44]
cannot install djangorestframework latest version(3.12.4) along with django-rest-authemail==2.0.6 version

when trying to install djangorestframework==3.12.4 and django-rest-authemail==2.0.6 via pip i get the error

> INFO: pip is looking at multiple versions of datetimerange to determine which version is compatible with other requirements. This could take a while.
> ERROR: Cannot install -r requirements.txt (line 16), django-rest-authemail==2.0.6 and djangorestframework==3.12.4 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested djangorestframework==3.12.4
>     django-rest-auth 0.9.5 depends on djangorestframework>=3.1.3
>     django-rest-authemail 2.0.6 depends on djangorestframework==3.11.0
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
> 

I need to import this into my code
`from rest_framework import filters
`
so that I could use
`filter_backends = [filters.SearchFilter]`

but due to this package's dependency error I am not able to use the same

**Comment by celiao** [comment]
This issue should be addressed by PR #42, which I just pulled
