### ISSUE TITLE
/users/me does not return user id

### ISSUE THREAD

**Issue by dnuske** [celiao/django-rest-authemail#48]
The readme says /users/me would return the user id.

the id is not coming through and the reason is the user serializer does not include that field.

```
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')
```

either the Readme or the serializer has to be updated

**Comment by dnuske** [comment]
just added a PR with the id, tested on my local and works as expected.
https://github.com/celiao/django-rest-authemail/pull/49

**Comment by merwok** [comment]
Isn’t `id` usually internal information, and `USERNAME_FIELD` what should be used from the outside?

**Comment by dnuske** [comment]
@merwok I don't think is a security risk to disclose an id of a record in the database, nobody can do anything with it. Most systems expose that kind of information without restrictions.

While it is possible to update all my views so that I can fetch user data by email instead of by id it's too much overhead of work for a feature that is already there as long as the user id is available. 

Additionally the readme shows that /users/me returns it, it was just not applied in the code.

**Comment by celiao** [comment]
`id` is returned after #49 was merged.
