### ISSUE TITLE
I am unable to add custom fields in MyUser

### ISSUE THREAD

**Issue by aishatasaduq** [celiao/django-rest-authemail#61]
this is my models.py file   
from django.db import models
from authemail.models import EmailUserManager, EmailAbstractUser

class MyUser(EmailAbstractUser):
	address = models.TextField('Address', blank=True)
	health_insurance = models.TextField('Health Insurance', blank=True)
	birthdate = models.DateField('Date of Birth', null=True, blank=True)
	double_opt_in = models.BooleanField('Double Opt-In', default=False)
	# Override first_name and last_name fields to make them required
	first_name = models.CharField('First Name', max_length=30, blank=False)
	last_name = models.CharField('Last Name', max_length=30, blank=False)
	# Required
	objects = EmailUserManager()  

these custom fields do not show in signup and also first_name and last_name are not required even when i have set them blank=False.

@celiao kindly tell me how to customize user?

**Comment by merwok** [comment]
Is your custom class defined as user model in settings?
Have you created migrations?
Do you have a custom signup serializer in settings?

**Comment by aishatasaduq** [comment]
yes i do have AUTH_USER_MODEL = 'interface.MyUser' in my settings and i have applied migrations.
No I don't have custom serializer.

**Comment by aishatasaduq** [comment]
serializer //
class UserRegistrationSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyUser
        fields = ('email', 'password', 'first_name', 'last_name', 'address', 'health_insurance', 'birthdate', 'double_opt_in')
        extra_kwargs = {
            'password': {'write_only': True},
            'first_name': {'required': True},
            'last_name': {'required': True}
        }  

view//
class UserRegistrationView(APIView):
    serializer_class = UserRegistrationSerializer
    
    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"message": "User registered successfully"}, status=status.HTTP_201_CREATED)  

url//
 path('register/', UserRegistrationView.as_view(), name='user-registration'),  

it doesn't send verification email. @celiao

**Comment by merwok** [comment]
You should use the signup view from this package, not make a custom one

**Comment by aishatasaduq** [comment]
thankyou. solved it :)
