### ISSUE TITLE
permission_classes  does not work with APIView

### ISSUE THREAD

**Issue by LennyLip** [celiao/django-rest-authemail#8]
permission_classes  does not work with APIView in DRF.
Its work only with GenericAPIView, or if we run 
self.check_object_permissions(self.request, obj)

see https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/generics.py#L98

**Comment by celiao** [comment]
`permission_classes` is used with an `APIView` in the DRF documentation here.  Closing.
- https://www.django-rest-framework.org/api-guide/permissions/

![image](https://user-images.githubusercontent.com/5824630/102727899-8f0afe00-42dd-11eb-8a34-107b1a16ba78.png)
