### ISSUE TITLE
Field name `username` is not valid for model `CustomUser`.

### ISSUE THREAD

**Issue by andreyshipilov** [celiao/django-rest-authemail#9]
Hey, I'm trying to implement everything by the docs, but get this error when trying to create a new user using the REST Framework registration.

```
    # installed apps
    ...
    'allauth',
    'allauth.account',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'authemail',
)
```

```
# settings

AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
}
```

```
# the model
from authemail.models import EmailUserManager, EmailAbstractUser
class CustomUser(EmailAbstractUser):
    objects = EmailUserManager()
    USERNAME_FIELD = 'email'
```

Posting this to the registration url:

```
# payload
{
    "email": "a@a.ru",
    "password1": "123456",
    "password2": "123456"
}
```

...creates a user with these credentials but the response from Django is:

```
ImproperlyConfigured at /rest-auth/registration/
Field name `username` is not valid for model `CustomUser`.
```

The user is created with this email and password, but the /registration/ url and /login/ url throws that error.

This is the traceback. http://pastebin.com/raw.php?i=d63tmZ7w

Am I missing something?

**Comment by celiao** [comment]
Hey Andrey.  It appears that you are trying to use [django-rest-authemail](https://github.com/celiao/django-rest-authemail) and [django-rest-auth](https://github.com/Tivix/django-rest-auth) simultaneously.  They are two completely separate packages for creating an API to handle user signup and authentication.  You want to use one or the other, and not both (e.g., only one of `authemail` and `rest_auth` should appear in your `settings.py` file).

To use [django-rest-authemail](https://github.com/celiao/django-rest-authemail), which allows users to enter their email address rather than a username to log in, look in the `example_project` directory.

**Comment by andreyshipilov** [comment]
Yep, my mistake. For some reason I thought the packages add to each other.

**Comment by celiao** [comment]
No problem.  Best of luck!

**Comment by Milutinke92** [comment]
@celiao Hi. I am also having this trouble.
I put everything as here in settings.py and still doesn't work.

I created custom user:
# settings
# nstalled apps
[...
# 3rd party
    'allauth',
    'allauth.account',
    'actstream',
    'corsheaders',
    'django_countries',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'rest_framework_gis',

    # Apps
    'authentication',


    'rest_framework_swagger',
]

# authentication 
AUTH_USER_MODEL = "authentication.MainUser"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

REST_FRAMEWORK = {
    #'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',

    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# model 
class MainUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    country = CountryField(_("country"))
    type = models.IntegerField(_('user type'), choices=const.USER_TYPES)
 is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text='Designates whether the user can log into this admin site.',
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'
    )

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['first_name', 'last_name']
    objects = UserManager()

Please help.

**Comment by e-harsley** [comment]
I am having the same problem where you able to solve it

**Comment by Etechdreams-github** [comment]
raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `First name` is not valid for model `User`.

**Comment by merwok** [comment]
Do you mind opening a new ticket?  And please include your model definition + relevant settings to help.
